### ISSUE TITLE
Traceback from 0 when there's no config

### ISSUE THREAD

**Issue by Dokman** [alzamer2/Crunchyroll-XML-Decoder-py3#10]
Traceback (most recent call last):
  File "F:\Repos\Crunchyroll-XML-Decoder-py3\crunchy-xml-decoder-py3.py", line 32, in <module>
    from login import login, getuserstatus
  File "crunchy-xml-decoder\login.py", line 6, in <module>
    from configparser import ConfigParser
ImportError: No module named configparser

PS: MY Python version is 3.7.3

**Comment by Dokman** [comment]
My fault, i think the path was executing 2.7 so my fix was to create a batch with this:

@echo off
"C:\Users\Your_User\AppData\Local\Programs\Python\Python37\python.exe" crunchy-xml-decoder-py3.py
