### ISSUE TITLE
Wierd Download error

### ISSUE THREAD

**Issue by reikitsune** [alzamer2/Crunchyroll-XML-Decoder-py3#11]
I'm trying to download a specific episode, and it doesn't want to download. I can go download from another series no problem. The episode is watchable thru the site. Here's what the program says:

Exception in thread download_thread_:
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "crunchy-xml-decoder\hls_.py", line 95, in download_thread
    self.download_part(seg.absolute_uri, output, key, seg.media_sequence, self.tasks1)
  File "crunchy-xml-decoder\hls_.py", line 62, in download_part
    with open(filename, 'ab') as f_handle:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\Public\\Crunchyroll-XML-Decoder_link\\export\\Phantom Thief Reinya Episode - 3 - Stolen Love in Space.".ts0'

Traceback (most recent call last):
  File "C:\Users\Public\Crunchyroll-XML-Decoder_link\crunchy-xml-decoder-py3.py", line 407, in <module>
    make_choise()
  File "C:\Users\Public\Crunchyroll-XML-Decoder_link\crunchy-xml-decoder-py3.py", line 355, in make_choise
    ultimate()
  File "crunchy-xml-decoder\ultimate.py", line 190, in ultimate
    download_.video_hls(hls_url, video_input, config_['connection_n_'])
  File "crunchy-xml-decoder\hls_.py", line 144, in video_hls
    self.fetch_streams()
  File "crunchy-xml-decoder\hls_.py", line 126, in fetch_streams
    os.rename(self.output+'0',self.output)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\Public\\Crunchyroll-XML-Decoder_link\\export\\Phantom Thief Reinya Episode - 3 - Stolen Love in Space.".ts0' -> 'C:\\Users\\Public\\Crunchyroll-XML-Decoder_link\\export\\Phantom Thief Reinya Episode - 3 - Stolen Love in Space.".ts'

Not sure if it was program or site related.

**Comment by alzamer2** [comment]
Can you post episode link? So I can test it out

**Comment by reikitsune** [comment]
https://www.crunchyroll.com/phantom-thief-reinya/episode-3-stolen-love-in-space-538956

**Comment by alzamer2** [comment]
I think I fix it
Update code and try that link

Sent from Mail for Windows 10

**Comment by reikitsune** [comment]
Working 100%. Thanks Alzamer2!
