### ISSUE TITLE
Batch download error

### ISSUE THREAD

**Issue by darkhelmet2016** [alzamer2/Crunchyroll-XML-Decoder-py3#22]
Traceback (most recent call last):
  File "C:\Users\Owner\Downloads\Crunchyroll-XML-Decoder-py3-master\crunchy-xml-
decoder-py3.py", line 645, in <module>
    menu_test.start_()
  File "crunchy-xml-decoder\pretyconsole.py", line 116, in start_
    self.run_menu('Main')
  File "crunchy-xml-decoder\pretyconsole.py", line 143, in run_menu
    output_ = function_[0](*function_[1], **function_[2])
  File "crunchy-xml-decoder\ultimate.py", line 91, in ultimate
    media_id = re.findall(r'https?://www\.crunchyroll\.com/.+/.+-(\d*)',page_url
)[0]
IndexError: list index out of range
Press any key to continue . . .

**Comment by darkhelmet2016** [comment]
NVM, can remove this
