### ISSUE TITLE
Error with latest version

### ISSUE THREAD

**Issue by fixx1983** [alzamer2/Crunchyroll-XML-Decoder-py3#25]
Just after the check of the installed requirements it shows:
```
Traceback (most recent call last):
  File "G:\Crunchyroll-XML-Decoder-master\crunchy-xml-decoder-py3.py", line 119, in <module>
    userstatus = getuserstatus()
  File "crunchy-xml-decoder\login.py", line 69, in getuserstatus
    sess_id_usa = create_sess_id_usa(payload_usa)
  File "crunchy-xml-decoder\login.py", line 167, in create_sess_id_usa
    if usa_session_post.json()['error'] != "true":
  File "C:\Users\fixx1\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\fixx1\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\fixx1\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\fixx1\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by alzamer2** [comment]
what rev are you using?

**Comment by fixx1983** [comment]
Latest one, Rev.20

**Comment by alzamer2** [comment]
try now

**Comment by fixx1983** [comment]
Works, thanks!
