### ISSUE TITLE
Error SSL certificate

### ISSUE THREAD

**Issue by fixx1983** [alzamer2/Crunchyroll-XML-Decoder-py3#32]
```
Please enter Crunchyroll video URL:
https://www.crunchyroll.com/it/food-wars-shokugeki-no-soma/episode-9-the-god-tongues-despair-796433
Traceback (most recent call last):
  File "C:\Users\fixx1\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\fixx1\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\fixx1\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\fixx1\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\fixx1\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "C:\Users\fixx1\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 950, in send
    self.connect()
  File "C:\Users\fixx1\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Users\fixx1\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\fixx1\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\fixx1\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "I:\Crunchyroll-XML-Decoder-master\crunchy-xml-decoder-py3.py", line 645, in <module>
    menu_test.start_()
  File "crunchy-xml-decoder\pretyconsole.py", line 116, in start_
    self.run_menu('Main')
  File "crunchy-xml-decoder\pretyconsole.py", line 143, in run_menu
    output_ = function_[0](*function_[1], **function_[2])
  File "crunchy-xml-decoder\ultimate.py", line 162, in ultimate
    hls_url_m3u8 = m3u8.load(hls_url)
  File "C:\Users\fixx1\AppData\Local\Programs\Python\Python38-32\lib\site-packages\m3u8\__init__.py", line 46, in load
    content, base_uri = http_client.download(uri, timeout, headers, verify_ssl)
  File "C:\Users\fixx1\AppData\Local\Programs\Python\Python38-32\lib\site-packages\m3u8\httpclient.py", line 27, in download
    resource = opener.open(uri, timeout=timeout)
  File "C:\Users\fixx1\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\fixx1\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\fixx1\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\fixx1\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\fixx1\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1123)>
```

It does the same with every serie

**Comment by alzamer2** [comment]
sorry for delay 
i made some fixing for code
try it and see if the error stay

**Comment by alzamer2** [comment]
since there is no replay from 1.3 rev.26 I will close this issue
