### ISSUE TITLE
No login

### ISSUE THREAD

**Issue by DevMiKeCL** [alzamer2/Crunchyroll-XML-Decoder-py3#33]
there is a problem with the log in
this one is always a guest

python version=3.8.5 64 bit
OS Version=Windows 10 10.0.16299 SP0
System Type=AMD64
Code Version=1.3 rev.24 (Up-To-Date)
Colorama : installed!
lxml : installed!
wget : installed!
Cryptography : installed!
cloudscraper : installed!
m3u8 : installed!
youtube_dl : installed!
BeautifulSoup : installed!
pager : installed!
Unidecode : installed!
psutil : installed!
User Name = Guest
Membership Type = Guest

i wrote my login
Login as ****** successfully.>>

but i'm still a guest

**Comment by Virusf** [comment]
crunchyroll we changed their subscription type
I guess the problem comes from there

**Comment by DevMiKeCL** [comment]
that's right, it might not take the current login

**Comment by alzamer2** [comment]
crunchy changed some of its api code that why the login was failing
i think i fixed it now
try it out

ps: sorry for delay i missed this issue and did not know it was posted

**Comment by darkhelmet2016** [comment]
Had to re-download the zip file because was giving an error trying to update.

trying to close Crunchyroll-XML-Decoder-py3.......
Press any key to continue . . . Traceback (most recent call last):
  File ".\crunchy-xml-decoder\updater.py", line 80, in <module>
    run_update()
  File ".\crunchy-xml-decoder\updater.py", line 67, in run_update
    wget.download('https://github.com/alzamer2/Crunchyroll-XML-Decoder-py3/archi
ve/master.zip',os.path.abspath(os.path.join(code_dir__,'update.zip')))
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\site-packag
es\wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\urllib\requ
est.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\urllib\requ
est.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\urllib\requ
est.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\urllib\requ
est.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\urllib\requ
est.py", line 563, in error
    result = self._call_chain(*args)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\urllib\requ
est.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\urllib\requ
est.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\urllib\requ
est.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\urllib\requ
est.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\urllib\requ
est.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\urllib\requ
est.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\urllib\requ
est.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

**Comment by alzamer2** [comment]
After you re-download zip, did it work for you?

**Comment by darkhelmet2016** [comment]
Yes, but the updater still should have been able to do it without having to. This is a frequent issue with trying to update it from within the program itself.

**Comment by alzamer2** [comment]
damn I forgot about the update issue
and I was wondering what I forgot while working at rev27 XD

**Comment by alzamer2** [comment]
ok @darkhelmet2016 
i updated the updater code
hope this update will work out with you

**Comment by alzamer2** [comment]
as there is no new post i will assume that the updater is working fine now
i will close this issue for now
