### ISSUE TITLE
Subtitles download error since last update.

### ISSUE THREAD

**Issue by nigoki2** [alzamer2/Crunchyroll-XML-Decoder-py3#35]
Hi.
I'm a french user. Since the last update I get this error after the video download:

------------------------------
---- Downloading Subtitle ----
------------------------------
Traceback (most recent call last):
  File "D:\Crunchyroll-XML-Decoder-py3-master\crunchy-xml-decoder-py3.py", line 389, in <module>
    menu_test.start_()
  File "crunchy-xml-decoder\pretyconsole.py", line 116, in start_
    self.run_menu('Main')
  File "crunchy-xml-decoder\pretyconsole.py", line 143, in run_menu
    output_ = function_[0](*function_[1], **function_[2])
  File "crunchy-xml-decoder\ultimate.py", line 427, in ultimate
    vilos_subtitle(page_url)
  File "crunchy-xml-decoder\altfuncs.py", line 621, in vilos_subtitle
    if i["language"] == Loc_lang[config_['language']]:
KeyError: 'Francais'
Appuyez sur une touche pour continuer...

There is no error with english subtitles in option.
Please help!
Thank you.

**Comment by alzamer2** [comment]
Will look into it

**Comment by DevMiKeCL** [comment]
------------------------------
---- Downloading Subtitle ----
------------------------------
Traceback (most recent call last):
  File "D:\Crunchyroll\main.py", line 15, in <module>
    crunchy_xml_decoder_py3.menu_test.start_()
  File "crunchy-xml-decoder\pretyconsole.py", line 116, in start_
    self.run_menu('Main')
  File "crunchy-xml-decoder\pretyconsole.py", line 143, in run_menu
    output_ = function_[0](*function_[1], **function_[2])
  File "D:\Crunchyroll\crunchy-xml-decoder-py3.py", line 112, in queueu
    ultimate(line.strip(), '', '')
  File "crunchy-xml-decoder\ultimate.py", line 427, in ultimate
    vilos_subtitle(page_url)
  File "crunchy-xml-decoder\altfuncs.py", line 621, in vilos_subtitle
    if i["language"] == Loc_lang[config_['language']]:
KeyError: 'Espanol'

in spanish too

thanks

**Comment by DevMiKeCL** [comment]
the previous version works ok in subtitles

Code Version=1.3 rev.24 (Need to Update the Code)

**Comment by nigoki2** [comment]
Any news ? :/

**Comment by alzamer2** [comment]
My bad
Will look into it

**Comment by alzamer2** [comment]
hi 
can you give me anime with french subtitle so i can test it on them

**Comment by nigoki2** [comment]
Sure!
https://www.crunchyroll.com/fr/shadowverse/episode-28-overlapping-answers-797201

**Comment by alzamer2** [comment]
ok 1.3 rev.27 is up
its fix for this issue
test it out

**Comment by nigoki2** [comment]
Thank you alzamer2!

**Comment by alzamer2** [comment]
ok
i will close this issue for now
