### ISSUE TITLE
Bad Gateway error

### ISSUE THREAD

**Issue by darkhelmet2016** [alzamer2/Crunchyroll-XML-Decoder-py3#39]
Traceback (most recent call last):
  File "C:\Users\Owner\Desktop\Crunchyroll-XML-Decoder-py3-master\crunchy-xml-de
coder-py3.py", line 389, in <module>
    menu_test.start_()
  File "crunchy-xml-decoder\pretyconsole.py", line 116, in start_
    self.run_menu('Main')
  File "crunchy-xml-decoder\pretyconsole.py", line 143, in run_menu
    output_ = function_[0](*function_[1], **function_[2])
  File "C:\Users\Owner\Desktop\Crunchyroll-XML-Decoder-py3-master\crunchy-xml-de
coder-py3.py", line 112, in queueu
    ultimate(line.strip(), '', '')
  File "crunchy-xml-decoder\ultimate.py", line 232, in ultimate
    download_subprocess_result = download_.video_hls(hls_url, video_input, confi
g_['connection_n_'])
  File "crunchy-xml-decoder\hls_.py", line 158, in video_hls
    self.video = find_best_video(uri)
  File "crunchy-xml-decoder\hls_.py", line 231, in find_best_video
    playlist = m3u8.load(uri)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\site-packag
es\m3u8\__init__.py", line 49, in load
    return _load_from_uri(uri, timeout, headers, custom_tags_parser)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\site-packag
es\m3u8\__init__.py", line 58, in _load_from_uri
    resource = urlopen(request, timeout=timeout)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\urllib\requ
est.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\urllib\requ
est.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\urllib\requ
est.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\urllib\requ
est.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\urllib\requ
est.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\urllib\requ
est.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
Press any key to continue . . .

**Comment by alzamer2** [comment]
Can you link the anime you are trying to download?

**Comment by darkhelmet2016** [comment]
The entire series for Re:ZERO -Starting Life in Another World- Director’s Cut (English Dub) https://www.crunchyroll.com/rezero-starting-life-in-another-world-/episode-1-the-end-of-the-beginning-and-the-beginning-of-the-end-801101 to https://www.crunchyroll.com/rezero-starting-life-in-another-world-/episode-13-the-self-proclaimed-knight-and-the-greatest-knight-thats-all-this-story-is-about-801120

**Comment by alzamer2** [comment]
just to make sure you have a premium account and you are logged into it, right?

if so try this branch
its still under experiment but its working
https://github.com/alzamer2/Crunchyroll-XML-Decoder-py3/tree/1.4

**Comment by darkhelmet2016** [comment]
Yes, am logged in as a paid account.

**Comment by alzamer2** [comment]
did you try 1.4?

**Comment by taskforce22** [comment]
Those episodes won't download on 1.3 for me as well.

However, I also personally can't get 1.4 beta to download those (or even any other file that 1.3 can.)   I get this with that fork on every link.

One of those episodes that doesn't work.

Booting up...

Please enter Crunchyroll video URL:
https://www.crunchyroll.com/rezero-starting-life-in-another-world-/episode-1-the-end-of-the-beginning-and-the-beginning-of-the-end-801101
Traceback (most recent call last):
  File "F:\crunchyripper\crunchy-xml-decoder-py3.py", line 389, in <module>
    menu_test.start_()
  File "crunchy-xml-decoder\pretyconsole.py", line 116, in start_
    self.run_menu('Main')
  File "crunchy-xml-decoder\pretyconsole.py", line 143, in run_menu
    output_ = function_[0](*function_[1], **function_[2])
  File "crunchy-xml-decoder\ultimate.py", line 90, in ultimate
    html_page_ = gethtml(page_url)
  File "crunchy-xml-decoder\altfuncs.py", line 414, in gethtml
    subprocess.call(['node','-v'],stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
NameError: name 'subprocess' is not defined
Press any key to continue . . .

A show that 1.3 works fine downloading.

Booting up...

Please enter Crunchyroll video URL:
https://www.crunchyroll.com/food-wars-shokugeki-no-soma/episode-12-the-perfect-rocks-796436
Traceback (most recent call last):
  File "F:\Crunchyroll-XML-Decoder-py3-1.4\crunchy-xml-decoder-py3.py", line 389, in <module>
    menu_test.start_()
  File "crunchy-xml-decoder\pretyconsole.py", line 116, in start_
    self.run_menu('Main')
  File "crunchy-xml-decoder\pretyconsole.py", line 143, in run_menu
    output_ = function_[0](*function_[1], **function_[2])
  File "crunchy-xml-decoder\ultimate.py", line 90, in ultimate
    html_page_ = gethtml(page_url)
  File "crunchy-xml-decoder\altfuncs.py", line 414, in gethtml
    subprocess.call(['node','-v'],stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
NameError: name 'subprocess' is not defined
Press any key to continue . . .

**Comment by alzamer2** [comment]
My bad
Try now

**Comment by taskforce22** [comment]
Thanks for the help with this.  

Now it won't even start up unfortunately.

Traceback (most recent call last):
  File "F:\Crunchyroll-XML-Decoder-py3-1.4\crunchy-xml-decoder-py3.py", line 27, in <module>
    from login import login, getuserstatus
  File "crunchy-xml-decoder\login.py", line 31, in <module>
    from altfuncs import config
  File "crunchy-xml-decoder\altfuncs.py", line 25, in <module>
    import browser_cookie3
ModuleNotFoundError: No module named 'browser_cookie3'
Press any key to continue . . .

**Comment by alzamer2** [comment]
sorry my bad
because its beta its not perfect 
Redownload and try now

**Comment by taskforce22** [comment]
Still got the same result no browser_cookie3.

**Comment by alzamer2** [comment]
Did you Redownload the code?
Can you post your full screen so I can see it?

**Comment by taskforce22** [comment]
Yeah, I completely deleted the old code and downloaded the new code just to be sure it wasn't being overwritten.

F:\Crunchyroll-XML-Decoder-py3-1.4>crunchy-xml-decoder-py3.bat
Traceback (most recent call last):
  File "F:\Crunchyroll-XML-Decoder-py3-1.4\crunchy-xml-decoder-py3.py", line 27, in <module>
    from login import login, getuserstatus
  File "crunchy-xml-decoder\login.py", line 31, in <module>
    from altfuncs import config
  File "crunchy-xml-decoder\altfuncs.py", line 25, in <module>
    import browser_cookie3
ModuleNotFoundError: No module named 'browser_cookie3'
Press any key to continue . . .

**Comment by alzamer2** [comment]
Hmm
I will look into it
For now dow you know how to manually download python package?
If so download browser_cookies3 and try the code

**Comment by taskforce22** [comment]
F:\Crunchyroll-XML-Decoder-py3-1.4>crunchy-xml-decoder-py3.bat
Traceback (most recent call last):
  File "F:\Crunchyroll-XML-Decoder-py3-1.4\crunchy-xml-decoder-py3.py", line 29, in <module>
    from ultimate import ultimate, mkv_merge
  File "crunchy-xml-decoder\ultimate.py", line 17, in <module>
    from hls_ import video_hls
  File "crunchy-xml-decoder\hls_.py", line 24
    ef __init__(self):
       ^
SyntaxError: invalid syntax
Press any key to continue . . .

Sorry, I didn't realize browser_cookie3 was a python module.

**Comment by alzamer2** [comment]
no idea how did this happen
change "ef init(self):"

to "def init(self):"

**Comment by taskforce22** [comment]
Well, I can't say if it is working or not, I had to reinstall python and now I'm getting this error on both the old and new versions.

Traceback (most recent call last):
  File "F:\Crunchyroll-XML-Decoder-py3-1.4\crunchy-xml-decoder-py3.py", line 40, in <module>
    __version__ = '%s.%s.%s' % get_lastest_version()[1]
NameError: name 'get_lastest_version' is not defined
Press any key to continue . . .

Any idea what might be causing it?

**Comment by Virusf** [comment]
Hello
I had the same problem as the 1st message on https://www.crunchyroll.com/fr/for-whom-the-alchemist-exists-the-movie/for-whom-the-alchemist-exists-the-movie-for-whom-the-alchemist-exists-806647

![Sans titre](https://user-images.githubusercontent.com/48204427/107069387-31c20200-67e2-11eb-8fa7-f281f7c1f449.png)

**Comment by darkhelmet2016** [comment]
Any update on this fix? Downloads are now starting to stall with no error codes.

**Comment by alzamer2** [comment]
Will look into it
I will fix beta so it can be fixed

**Comment by darkhelmet2016** [comment]
This same error is occurring more frequently.

Now Downloading - Armor Shop for Ladies & Gentlemen Episode 9 - I Am Armor
Exception in thread download_thread_:                                                     151MB/317MB                                                                                           |%48 @ 5.11Mb/s
Traceback (most recent call last):                                                          Part#167                                                                                            |%100.0
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "crunchy-xml-decoder\hls_.py", line 95, in download_thread
    self.download_part(seg.absolute_uri, output, key, seg.media_sequence, self.tasks1)
  File "crunchy-xml-decoder\hls_.py", line 59, in download_part
    response.raise_for_status()
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://a-vrv.akamaized.net/evs1/176936b195e94553c553edbfcd4abd19/assets/6a0593a8447250bb6a821265868334d2_3990825.mp4/seg-168-v1-a1.ts?t=exp=1614557640~acl=/evs1/176936b195e94553c553edbfcd4abd19/assets/6a0593a8447250bb6a821265868334d2_3990825.mp4/*~hmac=7e82a616b6c356e5624acbac68050501b9ae8f3cd749d3b02630bb694d6d4d76
