### ISSUE TITLE
BUG ANIME

### ISSUE THREAD

**Issue by SAOKT** [alzamer2/Crunchyroll-XML-Decoder-py3#43]
Hello.
for some reason this anime. can not be downloaded.
sell this bug.
all other anime without problems.
name: https://www.crunchyroll.com/es/so-im-a-spider-so-what

ERROR:
Booting up...

Now Downloading - So I'm a Spider, So What. Episode 1 - ?Reencarnacion. ?Otro mundo.
Exception in thread download_thread_:
Traceback (most recent call last):
  File "C:\Users\sao\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\sao\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "crunchy-xml-decoder\hls_.py", line 95, in download_thread
    self.download_part(seg.absolute_uri, output, key, seg.media_sequence, self.tasks1)
  File "crunchy-xml-decoder\hls_.py", line 62, in download_part
    with open(filename, 'ab') as f_handle:
OSError: [Errno 22] Invalid argument: "C:\\Users\\sao\\3D Objects\\Crunchyroll-XML-Decoder-py3-master\\export\\So I'm a Spider, So What. Episode - 1 - ?Reencarnacion. ?Otro mundo..ts0"

Traceback (most recent call last):
  File "C:\Users\sao\3D Objects\Crunchyroll-XML-Decoder-py3-master\crunchy-xml-decoder-py3.py", line 378, in <module>
    queueu(os.path.join('.', arg.queue))
  File "C:\Users\sao\3D Objects\Crunchyroll-XML-Decoder-py3-master\crunchy-xml-decoder-py3.py", line 112, in queueu
    ultimate(line.strip(), '', '')
  File "crunchy-xml-decoder\ultimate.py", line 232, in ultimate
    download_subprocess_result = download_.video_hls(hls_url, video_input, config_['connection_n_'])
  File "crunchy-xml-decoder\hls_.py", line 162, in video_hls
    self.fetch_streams()
  File "crunchy-xml-decoder\hls_.py", line 126, in fetch_streams
    os.rename(self.output+'0',self.output)
OSError: [WinError 123] El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos: "C:\\Users\\sao\\3D Objects\\Crunchyroll-XML-Decoder-py3-master\\export\\So I'm a Spider, So What. Episode - 1 - ?Reencarnacion. ?Otro mundo..ts0" -> "C:\\Users\\sao\\3D Objects\\Crunchyroll-XML-Decoder-py3-master\\export\\So I'm a Spider, So What. Episode - 1 - ?Reencarnacion. ?Otro mundo..ts"

**Comment by alzamer2** [comment]
The problem is in the name
It's try to save file in your hard disk with name contain '?'

**Comment by SAOKT** [comment]
how can I solve it?

I like your application.
I've tried others but they download the videos badly.
