### ISSUE TITLE
new mistake

### ISSUE THREAD

**Issue by SAOKT** [alzamer2/Crunchyroll-XML-Decoder-py3#44]
This error started to come out of nowhere today.
Do you have an account [Y/N]?
Traceback (most recent call last):
  File "C:\Users\SAO\Music\Crunchyroll-XML-Decoder-py3-master\crunchy-xml-decode
r-py3.py", line 363, in <module>
    check_cookies()
  File "C:\Users\SAO\Music\Crunchyroll-XML-Decoder-py3-master\crunchy-xml-decode
r-py3.py", line 90, in check_cookies
    login('', '')
  File "crunchy-xml-decoder\login.py", line 278, in login
    generate_sess_id = create_sess_id()
  File "crunchy-xml-decoder\login.py", line 242, in create_sess_id
    sess_id_data = session.post('http://api.crunchyroll.com/start_session.0.json
', proxies=proxies, params=payload).json()['data']
  File "C:\Users\SAO\AppData\Local\Programs\Python\Python37\lib\site-packages\re
quests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\SAO\AppData\Local\Programs\Python\Python37\lib\json\__init__.py
", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\SAO\AppData\Local\Programs\Python\Python37\lib\json\decoder.py"
, line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\SAO\AppData\Local\Programs\Python\Python37\lib\json\decoder.py"
, line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Presione una tecla para continuar . . .

**Comment by vampjoseph** [comment]
this is abandonware. I doubt anyone is working on fixes for the current code. time to move on, friend.

**Comment by alzamer2** [comment]
was busy in life
will go back to fix code soon

**Comment by vampjoseph** [comment]
I stand corrected. My apologies. please disregard my earlier message.
