### ISSUE TITLE
anime movie with the train error

### ISSUE THREAD

**Issue by tamodolo** [alzamer2/Crunchyroll-XML-Decoder-py3#46]
Now Downloading - The one anime with the train
Traceback (most recent call last):
  File "crunchy-xml-decoder-py3.py", line 389, in <module>
    menu_test.start_()
  File "crunchy-xml-decoder/pretyconsole.py", line 116, in start_
    self.run_menu('Main')
  File "crunchy-xml-decoder/pretyconsole.py", line 143, in run_menu
    output_ = function_[0](*function_[1], **function_[2])
  File "crunchy-xml-decoder/ultimate.py", line 232, in ultimate
    download_subprocess_result = download_.video_hls(hls_url, video_input, config_['connection_n_'])
  File "crunchy-xml-decoder/hls_.py", line 158, in video_hls
    self.video = find_best_video(uri)
  File "crunchy-xml-decoder/hls_.py", line 241, in find_best_video
    return find_best_video(best_stream.absolute_uri)
  File "crunchy-xml-decoder/hls_.py", line 231, in find_best_video
    playlist = m3u8.load(uri)
  File "/usr/local/lib/python3.6/dist-packages/m3u8/__init__.py", line 58, in load
    return _load_from_uri(uri, timeout, headers, custom_tags_parser, verify_ssl)
  File "/usr/local/lib/python3.6/dist-packages/m3u8/__init__.py", line 70, in _load_from_uri
    resource = urlopen(request, timeout=timeout, context=context)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

Normal episodes download fine.

**Comment by alzamer2** [comment]
Can you post url so I can test it?

**Comment by tamodolo** [comment]
Sure! Here it is:

https://www.crunchyroll.com/pt-br/demon-slayer-kimetsu-no-yaiba/demon-slayer-kimetsu-no-yaiba-the-movie-mugen-train-demon-slayer-kimetsu-no-yaiba-the-movie-mugen-train-819635

**Comment by alzamer2** [comment]
hi
just making sure but you have Premium  right?

**Comment by tamodolo** [comment]
I do have.

It's working for you?

**Comment by alzamer2** [comment]
I just uploaded new version of script
But it's still beta and under testing so you need to manually download it

**Comment by alzamer2** [comment]
my bad due to problem in my git program the push of new script was delayed
you can download it now from
https://github.com/alzamer2/Crunchyroll-XML-Decoder-py3/tree/1.4

**Comment by tamodolo** [comment]
thanks!

I have modifications to the script to run with Linux. If this is of your interest please create a second branch for me to submit it (it uses wine to run mkvmerge but I'm looking for solutions to run native mkvmerge

My UEFI reseted in the energy blink some time ago so I can't run my VM to test this. I'll do it later.

**Comment by alzamer2** [comment]
here is 1.4 for unix
https://github.com/alzamer2/Crunchyroll-XML-Decoder-py3/tree/1.4_unix

lets work togther to to make code use native unix without ysing wine

**Comment by alzamer2** [comment]
@tamodolo i did not use Linux system so i dont know how to download compatible mkvmerger and ffmpeg for that system that why i used wine to bybass this problem
