### ISSUE TITLE
Can't login anymore

### ISSUE THREAD

**Issue by nigoki2** [alzamer2/Crunchyroll-XML-Decoder-py3#47]
Hi.
Since yesterday your script worked with some minor troubleshootings, but since tokay login fails each time.

**Comment by alzamer2** [comment]
Will look into it

**Comment by nigoki2** [comment]
Without my VPN I can login.
There's sure a sort of captcha with it.
For now its works again :)

**Comment by alzamer2** [comment]
Normally vpn ip addresses are suspect ip for most site that check ipsInfact my vpn ip was blocked (not caption but fully blocked) Sent from Mail for Windows From: nigoki2Sent: Sunday, October 10, 2021 7:30 PMTo: alzamer2/Crunchyroll-XML-Decoder-py3Cc: alzamer2; CommentSubject: Re: [alzamer2/Crunchyroll-XML-Decoder-py3] Can't login anymore (#47) Without my VPN I can login.There's sure a sort of captcha with it.For now its works again :)—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by nigoki2** [comment]
This is the common error I get most of the time:

Booting up...

Traceback (most recent call last):
  File "D:\Crunchyroll-XML-Decoder-py3-master\crunchy-xml-decoder-py3.py", line 389, in <module>
    menu_test.start_()
  File "crunchy-xml-decoder\pretyconsole.py", line 116, in start_
    self.run_menu('Main')
  File "crunchy-xml-decoder\pretyconsole.py", line 143, in run_menu
    output_ = function_[0](*function_[1], **function_[2])
  File "D:\Crunchyroll-XML-Decoder-py3-master\crunchy-xml-decoder-py3.py", line 112, in queueu
    ultimate(line.strip(), '', '')
  File "crunchy-xml-decoder\ultimate.py", line 97, in ultimate
    htmlconfig = json.loads(re.findall(r'vilos\.config\.media = ({.*})',html_page_)[0])
IndexError: list index out of range
Appuyez sur une touche pour continuer...

**Comment by alzamer2** [comment]
This error happen when page failed to load media (its also happen if login failed or got cloudflare block)Will try to add line to explain this error Sent from Mail for Windows From: nigoki2Sent: Saturday, October 16, 2021 5:56 AMTo: alzamer2/Crunchyroll-XML-Decoder-py3Cc: alzamer2; CommentSubject: Re: [alzamer2/Crunchyroll-XML-Decoder-py3] Can't login anymore (#47) This is the common error I get most of the time:Booting up...Traceback (most recent call last):File "D:\Crunchyroll-XML-Decoder-py3-master\crunchy-xml-decoder-py3.py", line 389, in menu_test.start_()File "crunchy-xml-decoder\pretyconsole.py", line 116, in start_self.run_menu('Main')File "crunchy-xml-decoder\pretyconsole.py", line 143, in run_menuoutput_ = function_[0](function_[1], **function_[2])File "D:\Crunchyroll-XML-Decoder-py3-master\crunchy-xml-decoder-py3.py", line 112, in queueuultimate(line.strip(), '', '')File "crunchy-xml-decoder\ultimate.py", line 97, in ultimatehtmlconfig = json.loads(re.findall(r'vilos.config.media = ({.})',html_page_)[0])IndexError: list index out of rangeAppuyez sur une touche pour continuer...—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by alzamer2** [comment]
I just uploaded new version of script
But it's still beta and under testing so you need to manually download it

**Comment by alzamer2** [comment]
my bad due to problem in my git program the push of new script was delayed
you can download it now from 
https://github.com/alzamer2/Crunchyroll-XML-Decoder-py3/tree/1.4

**Comment by nigoki2** [comment]
I will wait a little longer since I get:

Traceback (most recent call last):
  File "crunchy-xml-decoder-py3.py", line 27, in <module>
    from login import login, getuserstatus
  File "crunchy-xml-decoder\login.py", line 31, in <module>
    from altfuncs import config
  File "crunchy-xml-decoder\altfuncs.py", line 26, in <module>
    import browser_cookie3
ModuleNotFoundError: No module named 'browser_cookie3'
Appuyez sur une touche pour continuer...

**Comment by alzamer2** [comment]
that werired , it should auto install it

**Comment by alzamer2** [comment]
can you post full text of console?

**Comment by nigoki2** [comment]
This is all the text of console when I launch crunchy-xml-decoder-py3

**Comment by alzamer2** [comment]
are you using 1.4 rev30, 31 or 32?

**Comment by nigoki2** [comment]
Hi.
This morning I managed to install 1.4 rev32.
But get this when downloading:

Booting up...
Please enter Crunchyroll video URL:>
https://www.crunchyroll.com/fr/platinum-end/episode-4-time-to-assemble-819760
Now Downloading - Platinum End Episode 4 - Time to Assemble [HLS stream]

error while downloading.......retry #1
error while downloading.......retry #2
error while downloading.......retry #3
error while downloading.......retry #4
error while downloading.......retry #5

------------------------------
---- Downloading Subtitle ----
------------------------------
Attempting to download Français (France) subtitle...
Starting mkv merge
Traceback (most recent call last):
  File "crunchy-xml-decoder-py3.py", line 402, in <module>
    menu_test.start_()
  File "crunchy-xml-decoder\pretyconsole.py", line 128, in start_
    self.run_menu('Main')
  File "crunchy-xml-decoder\pretyconsole.py", line 155, in run_menu
    output_ = function_[0](*function_[1], **function_[2])
  File "crunchy-xml-decoder-py3.py", line 134, in ultimate_
    ultimate_class.download(*arg,**kwarg)
  File "crunchy-xml-decoder\ultimate.py", line 310, in download
    mkv_merge(self.video_output, self.config_dict['video_quality'], 'English')
  File "crunchy-xml-decoder\ultimate.py", line 367, in mkv_merge
    cmd += ['--language', '0:' + re.findall(r'\[(.*)\]\[',file)[0],
UnboundLocalError: local variable 'cmd' referenced before assignment
Appuyez sur une touche pour continuer...

**Comment by nigoki2** [comment]
And now my old version doesn't work anymore :(

Traceback (most recent call last):
  File "D:\Crunchyroll-XML-Decoder-py3-master\crunchy-xml-decoder-py3.py", line 27, in <module>
    from login import login, getuserstatus
  File "crunchy-xml-decoder\login.py", line 29, in <module>
    from altfuncs import config
ModuleNotFoundError: No module named 'altfuncs'
Appuyez sur une touche pour continuer...

**Comment by alzamer2** [comment]
i just uploaded v1.4 rev33 #50 to fix this
try using it

**Comment by darkhelmet2016** [comment]
Getting a similar error.

Traceback (most recent call last):
  File "crunchy-xml-decoder-py3.py", line 27, in <module>
    from login import login, getuserstatus
  File "crunchy-xml-decoder\login.py", line 31, in <module>
    from altfuncs import config
  File "crunchy-xml-decoder\altfuncs.py", line 26, in <module>
    import browser_cookie3
ModuleNotFoundError: No module named 'browser_cookie3'
Press any key to continue . . .

**Comment by alzamer2** [comment]
ok i found the error
its problem with lines order
i will fix it with #48 
but for now just run crunchy-xml-decoder\external_test.py befoer you run the code will fix the problem

**Comment by alzamer2** [comment]
ok i think i fixed this error , try using lastest version and text it out

**Comment by nigoki2** [comment]
--------------------------
---- Start New Export ----
--------------------------
CrunchyRoll Downloader Toolkit DX v0.98b
Crunchyroll hasn't changed anything.

If you don't have a premium account, go and sign up for one now. It's well worth it, and supports the animators.

----------
Booting up...
Please enter Crunchyroll video URL:>
https://www.crunchyroll.com/fr/restaurant-to-another-world/episode-6-rice-burger-pizza-819260
Now Downloading - Restaurant to Another World Episode 6 - Rice Burger - Pizza [HLS stream]

error while downloading.......retry #1
error while downloading.......retry #2
error while downloading.......retry #3
error while downloading.......retry #4
error while downloading.......retry #5

------------------------------
---- Downloading Subtitle ----
------------------------------
Attempting to download English (US) subtitle...
Attempting to download Español subtitle...
Attempting to download Español (España) subtitle...
Attempting to download العربية subtitle...
Attempting to download Русский subtitle...
Attempting to download Italiano subtitle...
Attempting to download Français (France) subtitle...
Attempting to download Português (Brasil) subtitle...
Attempting to download Deutsch subtitle...
Starting mkv merge
Traceback (most recent call last):
  File "crunchy-xml-decoder-py3.py", line 412, in <module>
    menu_test.start_()
  File "crunchy-xml-decoder\pretyconsole.py", line 128, in start_
    self.run_menu('Main')
  File "crunchy-xml-decoder\pretyconsole.py", line 155, in run_menu
    output_ = function_[0](*function_[1], **function_[2])
  File "crunchy-xml-decoder-py3.py", line 144, in ultimate_
    ultimate_class.download(*arg,**kwarg)
  File "crunchy-xml-decoder\ultimate.py", line 325, in download
    mkv_merge(self.video_output, self.config_dict['video_quality'], 'English')
  File "crunchy-xml-decoder\ultimate.py", line 382, in mkv_merge
    cmd += ['--language', '0:' + re.findall(r'\[(.*)\]\[',file)[0],
UnboundLocalError: local variable 'cmd' referenced before assignment
Appuyez sur une touche pour continuer...

**Comment by alzamer2** [comment]
@nigoki2 just making sure
You are premium, right?

**Comment by darkhelmet2016** [comment]
I get a similar error but did not want to jack the tread for the issue. Was not sure if should of opened a new issue since it was about downloading and not logging.

**Comment by nigoki2** [comment]
Yes I'm premium.

**Comment by darkhelmet2016** [comment]
They changed it again and it produces new errors.
 File "crunchy-xml-decoder-py3.py", line 412, in <module>
    menu_test.start_()
  File "crunchy-xml-decoder\pretyconsole.py", line 128, in start_
    self.run_menu('Main')
  File "crunchy-xml-decoder\pretyconsole.py", line 155, in run_menu
    output_ = function_[0](*function_[1], **function_[2])
  File "crunchy-xml-decoder-py3.py", line 144, in ultimate_
    ultimate_class.download(*arg,**kwarg)
  File "crunchy-xml-decoder\ultimate.py", line 317, in download
    self.download_episode()
  File "crunchy-xml-decoder\ultimate.py", line 88, in download_episode
    self.htmlconfig = extract_streams(html_page_resp)
  File "crunchy-xml-decoder\altfuncs.py", line 778, in extract_streams
    asset_object = requests.get(beta_initialstate['content']['byId'][beta_initialstate['watch']['id']]['playback']).json()
KeyError: 'playback'
Press any key to continue . . .

**Comment by alzamer2** [comment]
What anime link?

**Comment by darkhelmet2016** [comment]
For me was https://www.crunchyroll.com/kagi-nado/episode-5-holiday-etc-821056.

**Comment by alzamer2** [comment]
Will look into it
