### ISSUE TITLE
Error when launching bat

### ISSUE THREAD

**Issue by nigoki2** [alzamer2/Crunchyroll-XML-Decoder-py3#52]
Hi.
I have this error when I launch the bat:

python version=3.7.7 64 bit
OS Version=Windows 10 10.0.19041 SP0
System Type=AMD64
Code Version=1.3 rev.29 (Up-To-Date)
Colorama : installed!
lxml : installed!
wget : installed!
Cryptography : installed!
cloudscraper : installed!
m3u8 : installed!
youtube_dl : installed!
BeautifulSoup : installed!
pager : installed!
Unidecode : installed!
psutil : installed!
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37\lib\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "C:\Program Files (x86)\Python37\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "C:\Program Files (x86)\Python37\lib\site-packages\urllib3\connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "C:\Program Files (x86)\Python37\lib\site-packages\urllib3\connection.py", line 370, in connect
    ssl_context=context,
  File "C:\Program Files (x86)\Python37\lib\site-packages\urllib3\util\ssl_.py", line 377, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Program Files (x86)\Python37\lib\ssl.py", line 423, in wrap_socket
    session=session
  File "C:\Program Files (x86)\Python37\lib\ssl.py", line 870, in _create
    self.do_handshake()
  File "C:\Program Files (x86)\Python37\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Program Files (x86)\Python37\lib\site-packages\urllib3\connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Program Files (x86)\Python37\lib\site-packages\urllib3\util\retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Program Files (x86)\Python37\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Program Files (x86)\Python37\lib\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "C:\Program Files (x86)\Python37\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "C:\Program Files (x86)\Python37\lib\site-packages\urllib3\connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "C:\Program Files (x86)\Python37\lib\site-packages\urllib3\connection.py", line 370, in connect
    ssl_context=context,
  File "C:\Program Files (x86)\Python37\lib\site-packages\urllib3\util\ssl_.py", line 377, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Program Files (x86)\Python37\lib\ssl.py", line 423, in wrap_socket
    session=session
  File "C:\Program Files (x86)\Python37\lib\ssl.py", line 870, in _create
    self.do_handshake()
  File "C:\Program Files (x86)\Python37\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(0, 'Error'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Crunchyroll-XML-Decoder-py3-master\crunchy-xml-decoder-py3.py", line 363, in <module>
    check_cookies()
  File "D:\Crunchyroll-XML-Decoder-py3-master\crunchy-xml-decoder-py3.py", line 94, in check_cookies
    userstatus = getuserstatus()
  File "crunchy-xml-decoder\login.py", line 124, in getuserstatus
    re_login_status = login(re_username, re_password)
  File "crunchy-xml-decoder\login.py", line 278, in login
    generate_sess_id = create_sess_id()
  File "crunchy-xml-decoder\login.py", line 236, in create_sess_id
    proxy_ = get_proxy(['HTTPS'], [config()['proxy']])
  File "crunchy-xml-decoder\proxy_cr.py", line 57, in get_proxy
    'https://www.xroxy.com/free-proxy-lists/?port=&type=Distorting&ssl=ssl&country='+countries_[0]+'&latency=&reliability=')
  File "C:\Program Files (x86)\Python37\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Program Files (x86)\Python37\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Program Files (x86)\Python37\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files (x86)\Python37\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files (x86)\Python37\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error'))
Appuyez sur une touche pour continuer...

**Comment by nigoki2** [comment]
Nevermind, it works again now...
