### ISSUE TITLE
The download and login no longer work

### ISSUE THREAD

**Issue by Askadelion** [alzamer2/Crunchyroll-XML-Decoder-py3#53]
The download and login no longer work, the following error occurs.

```

Password(don't worry the password are typing but hidden:
Traceback (most recent call last):
  File "D:\CRD-PY3\crunchy-xml-decoder-py3.py", line 363, in <module>
    check_cookies()
  File "D:\CRD-PY3\crunchy-xml-decoder-py3.py", line 88, in check_cookies
    login(username, password)
  File "crunchy-xml-decoder\login.py", line 278, in login
    generate_sess_id = create_sess_id()
  File "crunchy-xml-decoder\login.py", line 242, in create_sess_id
    sess_id_data = session.post('http://api.crunchyroll.com/start_session.0.json', proxies=proxies, params=payload).json()['data']
KeyError: 'data'

```
Code Version=1.3 rev.29 (Up-To-Date)

**Comment by nigoki2** [comment]
Hi.
Same error for me.
Please help us alzamer2!

**Comment by Teredic** [comment]
i have found a fix for the login.

Inside 'login.py', lines 177-179, Replace this : 

`  payload = {'device_id': device_id, 'api_ver': '1.0',
              'device_type': 'com.crunchyroll.crunchyroid', 'access_token': 'WveH9VkPLrXvuNm', 'version': '2313.8',
              'locale': 'jaJP', 'duration': '9999999999'}`

by this : 

`  payload = {'device_id': device_id, 'api_ver': '1.0',
              'device_type': 'com.crunchyroll.windows.desktop', 'access_token': 'LNDJgOit5yaRIWN', 'version': '2313.8',
              'locale': 'jaJP', 'duration': '9999999999'}`

But downloading still doesn't work because of cloudflare's captcha.
