### ISSUE TITLE
Autocatch issue

### ISSUE THREAD

**Issue by jnyfiveoh** [alzamer2/Crunchyroll-XML-Decoder-py3#8]
Weird issue I am encountering.  Pardon if it is user error.

When I attempt to use the auto catch link option it continuously starts to download:
The Rising of the Shield Hero Episode - 4 - Lullaby at Dawn.

This happens regardless if I try to use different links.

Current link attempted:
https://www.crunchyroll.com/konosuba-gods-blessing-on-this-wonderful-world

Is there a setting somewhere that tracks last incomplete file of some sort?

**Comment by alzamer2** [comment]
hi
did it got fixed?

**Comment by jnyfiveoh** [comment]
> hi
> did it got fixed?

Hello, 
It was user error.  I did not realize there was a queue file.  Currently looking at the app to see if there is a function to download only specific dub when using auto catch links

**Comment by alzamer2** [comment]
for now no,
but you can manually add the dub link to queue text so only the code download them

**Comment by jnyfiveoh** [comment]
> for now no,
> but you can manually add the dub link to queue text so only the code download them

Understood,
I did notice sometimes, when using queue option it will crash the app.
Other times it will ask for the url twice

**Comment by alzamer2** [comment]
can you send me links that crash it?

**Comment by jnyfiveoh** [comment]
> can you send me links that crash it?

https://www.crunchyroll.com/konosuba-gods-blessing-on-this-wonderful-world

I was assuming because it was attempting to catch all the other dub links.  When I edited and cleaned the queue.txt it seemed be happy

**Comment by alzamer2** [comment]
ok i think i know where the problem, but for now if you reduce the number of connection to 1 it will work out until i edit the code

**Comment by jnyfiveoh** [comment]
Understood.  Thanks for the update

**Comment by darkhelmet2016** [comment]
Unless you need the English dub you can set it to filter it out in the options under Dub Filter

**Comment by alzamer2** [comment]
@darkhelmet2016 
the problem are the dub video has lower parts than sub, the code has problem when spliting these part, i plan in next patch to add limiter for number of connection that linked to number of parts
for example dub link https://www.crunchyroll.com/konosuba-gods-blessing-on-this-wonderful-world/episode-2-an-explosion-for-this-chunibyo-780942
has only 13 part, when split to 8 connection, it will has some issue

**Comment by alzamer2** [comment]
maybe i will work into it nxt 2 days

**Comment by darkhelmet2016** [comment]
"Hello,
It was user error. I did not realize there was a queue file. Currently looking at the app to see if there is a function to download only specific dub when using auto catch links"

@alzamer2 Was more for the dub one he asked about and was thinking more of of a temp fix if he did not need more than the Japanese version

**Comment by alzamer2** [comment]
ok i did update the code and was able to download all episode of https://www.crunchyroll.com/konosuba-gods-blessing-on-this-wonderful-world (sub and dub) without problem
check it out and give me feedback

**Comment by darkhelmet2016** [comment]
----------
Booting up...

Traceback (most recent call last):
  File "C:\Users\Public\Crunchyroll-XML-Decoder_link\crunchy-xml-decoder-py3.py"
, line 407, in <module>
    make_choise()
  File "C:\Users\Public\Crunchyroll-XML-Decoder_link\crunchy-xml-decoder-py3.py"
, line 376, in make_choise
    queueu(os.path.join('.','queue.txt'))
  File "C:\Users\Public\Crunchyroll-XML-Decoder_link\crunchy-xml-decoder-py3.py"
, line 127, in queueu
    ultimate(line.rstrip('\n'), '', '')
  File "crunchy-xml-decoder\ultimate.py", line 79, in ultimate
    media_id = re.findall(r'https?://www\.crunchyroll\.com/.+/.+-(\d*)',page_url
)[0]
IndexError: list index out of range
Press any key to continue . . .

**Comment by alzamer2** [comment]
hmm
can you check queue file
i think there is problem in it

**Comment by darkhelmet2016** [comment]
Yea, think it copied the wrong url for the show and not the episode, but would still be a nice feature if you could just put in the shows url in the queue file and have it just download by the show instead of a dozen urls clogging it up.

**Comment by alzamer2** [comment]
i can do it, but he point of queue file is to control which episode to download even in bulk

i plan to make it check the link is show link or episode link, if show it will auto catch it to the queue file

**Comment by darkhelmet2016** [comment]
I know, but some of those shows have a hundred or more links like naruto or bleach. That is just a lot of clutter when you want to do back to back shows.

**Comment by alzamer2** [comment]
hmm
you know auto catch is function that extract link rom page then add them to queue file and run queue function, right?

**Comment by Dokman** [comment]
i have been bugged with usa proxy to download with autocatch and the program can't detect the links, so i don't know how to make it automatically but... that error i didn't have it.

**Comment by alzamer2** [comment]
are you sure that anime page opens in us?
some anime only for EU
can you give me link for that anime page?

**Comment by alzamer2** [comment]
here trick to check which contry that anime for
get anime page link
https://www.crunchyroll.com/military
and add .rss
https://www.crunchyroll.com/military.rss
then look for <media:restriction relationship="allow" type="country">
if "us" there then you should be able to view

**Comment by Dokman** [comment]
Ok i Will tell you tomorrow and thx as always <3

**Comment by alzamer2** [comment]
you are welcome

**Comment by Dokman** [comment]
i am in EU and i want to watch this one but the autocatch can't detect the anime
https://www.crunchyroll.com/granblue-fantasy-the-animation

**Comment by alzamer2** [comment]
hmm
i checked and this show can be viewed in us
are you sure your us setting is on?
here is links by the way
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-1-girl-in-blue-733307
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-2-departure-733309
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-3-meet-the-wind-733311
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-4-a-helmsmans-resolve-733313
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-5-the-storm-guardian-733315
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-6-the-veil-is-lifted-733317
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-7-the-iron-giant-733319
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-8-a-pair-apart-733321
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-9-horizon-in-the-clouds-733323
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-10-separation-733325
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-11-lyrias-wish-733327
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-12-showdown-on-the-high-seas-733329
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-13-another-sky-733331
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-1-skyfarers-in-the-blue-789458
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-2-the-albion-citadel-789459
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-3-false-freedom-789460
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-4-unconveyable-feelings-789461
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-5-katalina-and-vira-789462

**Comment by alzamer2** [comment]
hmm
i checked and this show can be viewed in us
are you sure your us setting is on?
here is links by the way
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-1-girl-in-blue-733307
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-2-departure-733309
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-3-meet-the-wind-733311
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-4-a-helmsmans-resolve-733313
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-5-the-storm-guardian-733315
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-6-the-veil-is-lifted-733317
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-7-the-iron-giant-733319
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-8-a-pair-apart-733321
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-9-horizon-in-the-clouds-733323
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-10-separation-733325
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-11-lyrias-wish-733327
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-12-showdown-on-the-high-seas-733329
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-13-another-sky-733331
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-1-skyfarers-in-the-blue-789458
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-2-the-albion-citadel-789459
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-3-false-freedom-789460
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-4-unconveyable-feelings-789461
http://www.crunchyroll.com/granblue-fantasy-the-animation/episode-5-katalina-and-vira-789462

**Comment by alzamer2** [comment]
hmm
i checked and this show can be viewed in us
are you sure your us setting is on?
here is links by the way

**Comment by Dokman** [comment]
i am using this settings
![image](https://user-images.githubusercontent.com/2290904/68243189-47121480-0012-11ea-8486-09f166facae2.png)

**Comment by alzamer2** [comment]
hmm
i want you to try 2 things
first is deleting queue file, some time if there some lines in queue file that code cant read it stop running
the other thing is to use links above to download at least 1 episode to make sure that code is running, and if it not , to see where the error happen

**Comment by Dokman** [comment]
i make it running with the links above and with a new queue file, but... when i try to make it with autocatch doesn't work 😓

**Comment by alzamer2** [comment]
ok so it seem only autocatch has problem then
will track it back

**Comment by alzamer2** [comment]
say when you try to autocatch does not just give you black screen then end without doing any thing
or there is error msg?

**Comment by alzamer2** [comment]
you see its working for me so i cantt found out the problem if i dont face it or there is error msg
ohh and can you paste here the link you fail autocatch with?

**Comment by Dokman** [comment]
okay idk what i've done it's working for me now, so i think the issue can be  closed, i've tested it with a new clone and it's working very well all

**Comment by alzamer2** [comment]
Maybe there was problem in 1of the files
And now it gone
If you get similar error try to screenshot it to track it back

**Comment by vampjoseph** [comment]
Sry to hijack and necro someone else's support ticket, but I have a problem with autocatch. As in when I select it from the menu, it spits out an error message and then closes the cmd window without allowing me to input my link.

The error is as follows:

Traceback (most recent call last):
  File "F:\Crunchyroll-XML-Decoder-py3\crunchy-xml-decoder-py3.py", line 645, in <module>
    menu_test.start_()
  File "crunchy-xml-decoder\pretyconsole.py", line 116, in start_
    self.run_menu('Main')
  File "crunchy-xml-decoder\pretyconsole.py", line 143, in run_menu
    output_ = function_[0](*function_[1], **function_[2])
  File "F:\Crunchyroll-XML-Decoder-py3\crunchy-xml-decoder-py3.py", line 536, in autocatch_t
    autocatch()
  File "crunchy-xml-decoder\altfuncs.py", line 371, in autocatch
    url = ''.join(re.findall(r'(https?://www\.crunchyroll\.com/)(?:[\w-]{2,5}/)?(.+?)(?=/|$)',url)[0])+'?skip_wall=1'
  File "C:\Python38\lib\re.py", line 239, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or bytes-like object
